version: "3.9"

services:
  db: 
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=laundry-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_DATABASES=laundry-app
      - REDIS_PASSWORD=12345
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: